"""Native module (Rust). The public API is :mod:`polars_psf`; these are its building blocks."""

from collections.abc import Iterator
from os import PathLike
from typing import Any

import polars as pl

class PsfError(ValueError):
    """Malformed or unsupported PSF data."""

class PsfFile:
    """A PSF result file (psfbin, psfascii or PSFXL stub + data)."""

    def __init__(self, path: str | PathLike[str]) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def is_swept(self) -> bool: ...
    @property
    def is_complete(self) -> bool: ...
    @property
    def layout(self) -> str: ...
    @property
    def is_psfxl(self) -> bool: ...
    @property
    def sweep_name(self) -> str | None: ...
    @property
    def names(self) -> list[str]: ...
    @property
    def header(self) -> dict[str, Any]: ...
    @property
    def psfxl_meta(self) -> dict[str, Any]: ...
    def props(self, name: str) -> dict[str, Any]: ...
    def units(self, name: str) -> str | None: ...
    def schema(self, names: list[str] | None = None) -> Any:
        """Empty Arrow record batch (PyCapsule) with the schema of ``read(names)``."""
    def read(self, names: list[str] | None = None) -> Any:
        """Arrow record batch (PyCapsule) with field metadata (``psf:units``, ...)."""
    def to_polars(self, names: list[str] | None = None) -> pl.DataFrame: ...
    def to_polars_long(self, names: list[str] | None = None, field: str | None = None) -> pl.DataFrame: ...
    def names_with_field(self, field: str) -> list[str]: ...
    def long_schema(self, field: str | None = None) -> Any: ...
    def read_signal(self, name: str) -> pl.DataFrame: ...
    def values(self) -> dict[str, Any]: ...
    def value(self, name: str) -> Any: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...

class BatchIter(Iterator[list[Any]]):
    """Batches of a scan: each step is a list of Arrow record batches read in parallel."""

    def __iter__(self) -> BatchIter: ...
    def __next__(self) -> list[Any]: ...

class ResultDir:
    """A result directory (logFile / runObjFile) or one PSF file as a one-leaf directory."""

    def __init__(self, path: str | PathLike[str]) -> None: ...
    @property
    def root(self) -> str: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def is_single_file(self) -> bool: ...
    def results(self) -> list[tuple[str, str, list[str], int]]: ...
    def resolve(self, result: str) -> str: ...
    def leaf_table(self, result: str) -> Any: ...
    def leaf_path(self, result: str, leaf: int) -> str: ...
    def sweep_name(self, result: str) -> str | None: ...
    def schema(self, result: str, names: list[str] | None = None) -> Any: ...
    def long_schema(self, result: str, field: str | None = None) -> Any: ...
    def signal_names(self, result: str, field: str | None = None) -> list[str]: ...
    def scan(
        self, result: str, leaves: list[int], names: list[str] | None = None, batch: int | None = None
    ) -> BatchIter: ...
    def scan_long(
        self,
        result: str,
        jobs: list[tuple[int, list[str] | None]],
        field: str | None = None,
        chunk_rows: int = ...,
        batch: int | None = None,
    ) -> BatchIter: ...
